ALTER TABLE users ADD COLUMN IF NOT EXISTS bio VARCHAR(160) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_data_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_genres VARCHAR(240) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS mood_tags VARCHAR(240) NOT NULL DEFAULT '';
